language: node_js
node_js:
  - 12

before_install:
  - npm i -g tsc
  - npm i -g create-react-app

script:
  - cd opentestplatform-backend && npm run build
  - cd ../opentestplatform-client && npm run build

cache:
  npm: false