services: mongodb

language: node_js
node_js:
  - 12

before_install:
  - npm i -g create-react-app
  - npm i -g react-scripts
  - npm install -g concurrently

script:
  - cd opentestplatform-backend && npm i && npm install ts-node --save-dev && npm install typescript --save-dev && npm i -g typescript && npm run build
  - mv .env.example .env
  - npm run test-dev
  - cd ../opentestplatform-client && npm i &&  CI=false npm run build

cache:
  npm: false