language: node_js
node_js:
  - 12

before_install:
  - npm i -g create-react-app
  - npm i -g react-scripts

script:
  - cd opentestplatform-backend && npm i && npm i typescript && npm run build
  - cd ../opentestplatform-client && npm i && npm run build

cache:
  npm: false