# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  app:
    image: docker.io/library/testowybackend:latest
    restart: always
    ports:
      - 8080:8080
    links:
      - "db:database"