# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '* * * * *'
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
       ref: API-change-node-to-java
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bootJar
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
      uses: docker/build-push-action@v2.6.1
      with:
        file: opentestplatform-backend/tools/docker/Dockerfile
        context: .
